"""add phase 8b remediation and execution fields

Revision ID: 947bc111ef32
Revises: 97d921a2148f
Create Date: 2026-09-03 10:15:34.026601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947bc111ef32'
down_revision = '97d921a2148f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remediation_change_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('remediation_action', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('remediation_target', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('remediation_preconditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('remediation_dependencies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('remediation_safety_checks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('approval_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('approval_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('execution_status', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('execution_evidence', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('executed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_column('executed_at')
        batch_op.drop_column('execution_evidence')
        batch_op.drop_column('execution_status')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approval_reference')
        batch_op.drop_column('approval_status')
        batch_op.drop_column('remediation_safety_checks')
        batch_op.drop_column('remediation_dependencies')
        batch_op.drop_column('remediation_preconditions')
        batch_op.drop_column('remediation_target')
        batch_op.drop_column('remediation_action')
        batch_op.drop_column('remediation_change_type')

    # ### end Alembic commands ###
