"""add incident model

Revision ID: 97d921a2148f
Revises: d42fc1e4e782
Create Date: 2026-08-27 03:37:16.277797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d921a2148f'
down_revision = 'd42fc1e4e782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('application', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('pipeline_name', sa.String(length=200), nullable=True),
    sa.Column('pipeline_run_id', sa.String(length=100), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('candidate_revision', sa.String(length=150), nullable=True),
    sa.Column('previous_revision', sa.String(length=150), nullable=True),
    sa.Column('failed_endpoints', sa.Text(), nullable=True),
    sa.Column('failure_summary', sa.Text(), nullable=True),
    sa.Column('rca_summary', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_incident_number'), ['incident_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_incident_number'))

    op.drop_table('incidents')
    # ### end Alembic commands ###
