"""add unique constraint for product name and category

Revision ID: d42fc1e4e782
Revises: 7144149b6bda
Create Date: 2026-08-13 08:58:20.080702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42fc1e4e782'
down_revision = '7144149b6bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_product_name_category', ['name', 'category'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_name_category', type_='unique')

    # ### end Alembic commands ###
